### PR TITLE
Add support for the local agent for service queries

### PR DESCRIPTION
**Pull request by roberteckert**
- Represent Consul data as a nested struct to allow
  slightly more reusability
- Move app generation to its own method attached to the new
  struct ConsulServiceData
- queryServices inspects the addr to determine whether it should
  use the local agent path or the provided address

### CODE REVIEW

**Comment by mayuresh82** [comment]
Could you please resolve the merge conflicts and re-send the PR

**Comment by roberteckert** [comment]
Fixed merge conflicts.

**Comment by cthayer** [comment]
@mayuresh82 Any updates on this PR?  Let me know how we can help get this merged.

**Comment by mayuresh82** [comment]
Hey @roberteckert  , from what I see in this PR, it only adds some reusability enhancements. Can you please re-name the PR to reflect that ? The local agent querying support was already landed in #3  unless I am missing something ?

**Comment by mayuresh82** [comment]
closing since no comment. please openup a new PR if necessary.

**Pull request closed without merging**
